### ISSUE TITLE
remove http dependency

### ISSUE THREAD

**Issue by ChristophP** [ChristophP/elm-i18next#13]
If updates to http are published the lib always needs to be kept in sync because elm doens't support multiple version of the same library.

**Comment by ChristophP** [comment]
@allanderek Unfortunately it's not that easy. There's a function called `fetchTranslations` which depends on `Http`. So that function would have to be removed as well.
I am hesitant because it would be a breaking change. On the other hand I wonder if anyone is using that function at all since it isn't very flexible (no custom headers, can only fetch one at a time).
Can you tell me if you have ever used it or just went with the decoder?
I would like to get rid of it because recently there has been an update for `elm/http` from 1 to 2 and since elm doesn't support multiple versions of the same package if I leave it in there that means
a) either I do nothing but then ppl using http2 cannot use this package
b) or I update it to http 2 but then people using http 1 will not get any updates on this package.

**Comment by allanderek** [comment]
Hi,

Yeah I had assumed your issue was a suggestion to remove the
'fetchTranslations' function as well, so that's what the pull request does.
I personally never used that. I think it is fine to remove it, anyone using
it should have no problems defining it themselves. The advantage of not
being tied to a particular version of 'elm/http' is a string one in my
opinion.

Allan.

**Comment by ChristophP** [comment]
@allanderek Oh great. I must have read the PR wrong the first time because I thought it only removed the dependency from the `elm.json`. I will merge and do the rest. Thanks for contributing.
