### ISSUE TITLE
Elm 0.19 support?

### ISSUE THREAD

**Issue by muelli** [ChristophP/elm-i18next#8]
Hi,

do you have any interest in supporting Elm 0.19?
Would you accept patches that make the code Elm 0.19 compatible?

**Comment by ChristophP** [comment]
Hi @muelli , thanks for the interest. The lib has actually been supporting 0.19 basically since its release. However for some reason I seem to have forgotten to merge the branch into master. It's called `chore/update-to-0.19. I'll try to clean up that mess.
You don't have to wait for that though. You can just go ahead and install the latest version 3.0.1 from elm package which works with 0.19 like I said.

**Comment by ChristophP** [comment]
So I merged the 0.19 changes for the lib. I also opened another PR to update the the tests and example to 0.19 as well so there shouldn't be any more confusion around whether or not 0.19 is supported. Thanks for making me aware of this.

**Comment by ChristophP** [comment]
Everything is merged to master now. Tests and examples are also updated to 0.19. So it should be obvious now that 0.19 is supported.
